config/routes.rb
Rails.application.routes.draw do
  root  to: "tickets#index"
  get "/tickets", to: "tickets#index"
  
  resources :tickets do 
    get :search, on: :collection
  end 
  resources :sessions
  resources :hour_sessions

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hour_session.rb
class HourSession < ApplicationRecord
  belongs_to :session
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/session.rb
class Session < ApplicationRecord
  validates :day, presence: true
  belongs_to :ticket
  
  has_many :hour_sessions, dependent: :delete_all
  accepts_nested_attributes_for :hour_sessions, reject_if: :all_blank, allow_destroy: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
      include PgSearch
      extend FriendlyId

      validates :title,  presence: :true
      validates :price, numericality:{greater_than: 0}

      has_many :sessions, dependent: :delete_all
      accepts_nested_attributes_for :sessions

      friendly_id :title, use: :slugged

      pg_search_scope :search,
            agaist: %i[title description],
            associated_agaist: {sessions: %i[day]}
            
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def index
    end
end

app/controllers/hour_sessions_controller.rb
class HourSessions_Controller < ApplicationController
    before_action :set_hourSessions, only: %i[ show edit update destroy ]

    def create
        hourSession = HourSession.create!(hourSessions_params)
        redirect_to session.ticket, notice: 'Hora adicionada'
    end

    def destroy
        @hourSession.destroy
    
        respond_to do |format|
          format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
          format.json { head :no_content }
        end
      end

    private 

    def hourSessions_params
        params.require(:hourSession).permit(:hour, :session_id)
    end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :set_sessions, only: %i[ show edit update destroy ]

    def new
      @session = Session.new
      @session = @ticket.sessions.build
      @hourSession = @sessions.hour_sessions.build
    end

    def create
      session = Session.create(sessions_params)
      respond_to do |format|
        format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    def show
      @ticket = Ticket.new(sessions_params)
      @session = @ticket.sessions.build
      @hourSession = HourSession.new
      @hourSessions = @session.hour_sessions
    end

    def destroy
        @sessions.destroy
    
        respond_to do |format|
          format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
          format.json { head :no_content }
        end
      end

    private 

    def sessions_params
        params.require(:session).permit(:day, :ticket_id)
    end 

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]

  # GET /tickets or /tickets.json
  def index
    @tickets = Ticket.order(created_at: :desc)
  end

  def search
    @tickets = Ticket.search(search_params[:q])
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
    @sessions = @ticket.sessions.build
  end

  # GET /tickets/1 or /tickets/1.json
  def show
    @session = Session.new
    @sessions = @ticket.sessions
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    if @ticket.save
      redirect_to ticket_path(@ticket)
    else
      render action: :new
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  
    def set_ticket
      @ticket = Ticket.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:title, :price, :description, :date_int, :date_out, :selling, :max_capacity, sessions_attributes: [:id, :day, :_destroy], hourSessions_attributes: [:id, :hour, :_detroy])
    end
def search_params
  params.permit(:q)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='pt'>
  <head>
    <title>Cinema</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all'%>
    <%= javascript_pack_tag 'application'%>
  </head>

  <body>
    <form class="row row-cols-lg-auto g-3 align-items-center offset-8">
      <div class="col-12">
        <div class="search">
          <%= form_with url: search_tickets_path, method: :get, local: true, class: 'form-inline' do |form| %>
            <div class='form-group mx-3 mb-3'>
              <%= form.search_field :q, class: 'form-control', required: true, placeholder: 'Busca', value: params[:q] %>
            </div>
        </div>
      </div>
      <div class="col-12">
          <%= form.submit 'Buscar', class: 'btn btn-primary mb-3', data: { disable_with: 'Buscando...' } %>
        <% end %>
      </div>
    </form>

    <%= yield %>
  </body>
</html>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  
  <div class="container px-0 mb-2">
    <div class="row gx-5 row-cols-5">
      <div class="col">
        <div class="form-group">
          <%= form.label :price %>
          <%= form.number_field :price, class: 'form-control' %>
        </div>
      </div>
    </div> 
  </div>   

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control', rows:5 %>
  </div>

  <div class="container px-0 mb-2">
    <div class="row gx-5 row-cols-5">

      <div class="col">
        <div class="form-group">
          <%= form.label :date_int %> 
          <%= form.date_field :date_int , class: 'form-control' %>
        </div>
      </div>

      <div class="col">
        <div class="form-group">
          <%= form.label :date_out %>
          <%= form.date_field :date_out, class: 'form-control' %>
        </div>
      </div>
      
    </div>
  </div>

  <div class="form-check form-switch">
    <%= form.label :selling %>
    <%= form.check_box :selling, class: 'form-check-input' %>
  </div>  

    <div id="sessions">
      <%= form.fields_for :sessions do |session| %>
        <%= render 'session_fields', f: session %>
      <%end%>  
      <div>
        <%= link_to_add_association "Adicionar sessão", form, :sessions, class: 'btn btn-info'%>
      </div>
    </div> 
  <br>
  <%= form.submit class: 'btn btn-primary', data: {disable_with: 'Criando'} %> 
  <%= link_to 'Voltar', tickets_path, class: 'btn btn-secondary' %>
<% end %>

app/views/tickets/_hourSession_fields.html.erb
<div class="container px-0 mb-2">
  <div class="row gx-5 row-cols-5">
    <div class="col">
      <div class="nested-fields">
        <div class="field">
            <%= f.label :hour %>
            <%= f.text_field :hour, class: 'form-control data-b mb-2' %>
        </div>
      </div>
    </div>  
  </div>
</div>  

app/views/tickets/_session_fields.html.erb
<div class="container px-0 mb-2">
  <div class="row gx-5 row-cols-5">
    <div class="col">
      <div class="nested-fields">
        <div class="field">
        <div class=" form-group">
            <%= f.label :day %>
            <%= f.date_field :day, class: 'form-control data-b mb-5' %>
            <%= link_to_remove_association "Remover Sessão", f, class:"btn btn-danger" %>
          </div>  
        </div>
      </div>
    </div>  
  </div>
</div>  

app/views/tickets/edit.html.erb
<div class="container">
    <h1>Editar Filme</h1>

    <%= render 'form', ticket: @ticket %>
</div>    

app/views/tickets/index.html.erb
<div class="container">
  <h1>Filmes</h1>
  <table class="table table-striped table-hover border-top">
    <thead>
      <tr>
        <th>Filme</th>
        <th>Preço</th>
        <th>Descrição</th>
        <th class="text-center" >Vendendo</th>
        <th>Data de Estreia</th>
        <th>Sai de cartaz</th>
        <th colspan="6"></th>
      </tr>
    </thead>

    <tbody>
      <% @tickets.each do |ticket| %>
        <tr>
          <td class= "td" >
            <%= link_to ticket, class:'text-black' do %>
              <%= ticket.title.truncate(25) %>
            <% end%>  
          </td>
          <td class= "td"><%= ticket.price %></td>
          <td class= "td-description"><%= ticket.description.truncate(30)  %></td>
          <td class="td-selling">
            <img src= "<%= ticket.selling == true ? "../../assets/check.png" : "src= ../../assets/erro.png" %>" class="img-selling">
          </td>
          <td class= "td"><%= ticket.date_int == nil ? ticket.date_int : l(ticket.date_int) %></td>
          <td class= "td"><%= ticket.date_out == nil ? ticket.date_out : l(ticket.date_out) %></td>
           <div class="btn-group" role="group" aria-label="Basic example">
            <td>
              <%= link_to 'Mostrar', ticket, class:'btn btn-primary'%>
              <%= link_to 'Editar', edit_ticket_path(ticket), class:'btn btn-primary'%>
              <%= link_to 'Excluir', ticket, method: :delete, data: { confirm: 'Tem certeza que deseja excluir esse registro ?' }, class:'btn btn-danger'%>
            </td>
          </div>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>

  <%=link_to "Novo Filme", new_ticket_path, class:"btn btn-success"%>
  </div>

app/views/tickets/new.html.erb
<div class="container">
    <h1>Novo Filme</h1>

    <%= render 'form', ticket: @ticket %>
</div>

app/views/tickets/search.html.erb
<div class="text-muted">
    <% if @tickets.any?%>
        <%= @tickets.count%> resultados encontrados
    <% else %>
        Nenhum resultado encontrado
    <% end %>
</div> 

<div class="text-right">
    <%= link_to "Criar novo Filme", new_ticket_path, class: 'btn btn-primary' %>

app/views/tickets/show.html.erb
<div class = "container mt-4">
    <h1>Visualizar</h1>
    <div class="shadow p-3 mb-5 bg-body rounded">
        <div class="card-body">
            <h5 class="card-title"><%= @ticket.title%></h5>
            <hr>
            Em cartaz de <b><%= @ticket.date_int != nil ? l(@ticket.date_int) : @ticket.date_int %></b> até <b><%= @ticket.date_out != nil ? l(@ticket.date_out) : @ticket.date_out %></b><br> 
            Vendendo: <img src= "<%= @ticket.selling == true ? "../../../assets/check.png" : "src= ../../../assets/erro.png" %>" class="img-selling-show">
            <p>Preço: R$<%= @ticket.price%> </p>
            <hr>
            <h5>Descrição</h5>
            <p class="card-text"><%= @ticket.description.gsub("\n","<br>").html_safe %></p>
            <p class="card-text"><small class="text-muted">Ultima Alteração da descrição: <%= l(@ticket.updated_at, format: :short ) %></small></p>
            <hr>

            <div class="container px-0 mb-2">
                <div class="row justify-content-start">
                    <div class="col-2">
                        <% @sessions.each do |sessions| %>
                            <div class="col"><%= sessions.day %></div>
                        <%end%>
                    </div>
                </div>
            </div> 
        </div>   
    </div>
    
    <%= link_to 'Editar' , edit_ticket_path(@ticket), class:"btn btn-success" %>
    <%= link_to 'Voltar', tickets_path , class:"btn btn-secondary" %>  
</div>